const vehicles=[
 {name:'Patient Van',subtitle:'เหมาะกับผู้สูงอายุและผู้ป่วยอาการคงที่',image:2,who:'ผู้ที่นั่งได้ และขึ้นลงรถได้โดยมีผู้ช่วย',equipment:'ที่นั่งสะดวกสบาย พื้นที่สำหรับญาติ',price:'2,500',condition:0},
 {name:'Wheelchair Van',subtitle:'รองรับรถเข็นและทางลาด',image:3,who:'ผู้ใช้รถเข็น ผู้สูงอายุที่ต้องการทางลาด',equipment:'ทางลาดหรือ Lift และจุดยึดรถเข็น',price:'3,000',condition:1},
 {name:'Stretcher Van',subtitle:'สำหรับผู้ป่วยนอนราบ / เคลื่อนย้าย',image:4,who:'ผู้ที่ต้องนอนราบระหว่างเดินทาง',equipment:'เตียง Stretcher และอุปกรณ์เคลื่อนย้าย',price:'3,500',condition:2},
 {name:'Medical Transport',subtitle:'มี O₂ / อุปกรณ์เพิ่มเติม / ผู้ช่วยดูแล',image:5,who:'ผู้ที่ต้องใช้อุปกรณ์เพิ่มเติมตามการประเมิน',equipment:'ออกซิเจนและอุปกรณ์ตามที่ตกลง',price:'4,500',condition:2}
];
const conditions=[['พอเดินได้','มีคนช่วยพยุง',6],['ใช้ Wheelchair','ต้องมีทางลาดหรือ Lift',7],['นอนราบ / ติดเตียง','ต้องใช้ Stretcher',8],['ต้องใช้ออกซิเจน','มีอุปกรณ์ระหว่างทาง',9]];
document.querySelector('#conditions').innerHTML=conditions.map((c,i)=>`<button class="condition" data-condition="${i}" aria-pressed="false"><img src="assets/image-${c[2]}.webp" alt="${c[0]}" loading="lazy"><div><strong>${c[0]}</strong><small>${c[1]}</small><em>ดูรถที่เหมาะสม</em></div></button>`).join('');
document.querySelector('#vehicle-list').innerHTML=vehicles.map((v,i)=>`<article class="vehicle"><img src="assets/image-${v.image}.webp" alt="${v.name}" loading="lazy"><div class="vehicle-body"><h3>${v.name}</h3><p class="subtitle">${v.subtitle}</p><dl class="details"><div><dt>เหมาะกับใคร</dt><dd>${v.who}</dd></div><div><dt>มีอะไรบ้าง</dt><dd>${v.equipment}</dd></div></dl><p class="price">เริ่มต้น <strong>${v.price} บาท</strong></p><button class="button outline" data-vehicle="${i}">เลือกรถประเภทนี้</button></div></article>`).join('');
const condition=document.querySelector('#condition'),oxygen=document.querySelector('#oxygen'),dialog=document.querySelector('dialog');
function updateRecommendation(){const index=oxygen.value==='yes'?3:Number(condition.value),v=vehicles[index];document.querySelector('#rec-title').textContent=v.name;document.querySelector('#rec-image').src=`assets/image-${v.image}.webp`;document.querySelector('#rec-text').textContent=v.who;return v;}
function choose(index){condition.value=String(vehicles[index].condition);oxygen.value=index===3?'yes':'no';updateRecommendation();document.querySelectorAll('.condition').forEach((el,i)=>{el.classList.toggle('selected',i===index);el.setAttribute('aria-pressed',String(i===index));});document.querySelector('#assessment').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
document.querySelectorAll('[data-condition]').forEach(el=>el.addEventListener('click',()=>choose(Number(el.dataset.condition))));document.querySelectorAll('[data-vehicle]').forEach(el=>el.addEventListener('click',()=>choose(Number(el.dataset.vehicle))));condition.addEventListener('change',updateRecommendation);oxygen.addEventListener('change',updateRecommendation);
const date=document.querySelector('[name=date]');const today=new Date();date.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
document.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target),v=updateRecommendation();document.querySelector('#summary-text').textContent=`จุดรับ: ${data.get('pickup')}\nจุดส่ง: ${data.get('destination')}\nวันเดินทาง: ${new Date(data.get('date')+'T12:00:00').toLocaleDateString('th-TH',{dateStyle:'long'})}\nสภาพผู้เดินทาง: ${condition.selectedOptions[0].text}\nอุปกรณ์: ${oxygen.selectedOptions[0].text}\nรถที่แนะนำเบื้องต้น: ${v.name}\nราคาเริ่มต้นตัวอย่าง: ${v.price} บาท (รอยืนยันราคาจริง)`;document.querySelector('#copy-status').textContent='';dialog.showModal();});
document.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});document.querySelector('#copy-summary').onclick=async()=>{try{await navigator.clipboard.writeText(document.querySelector('#summary-text').textContent);document.querySelector('#copy-status').textContent='คัดลอกข้อมูลแล้ว';}catch{document.querySelector('#copy-status').textContent='กรุณาเลือกและคัดลอกข้อความด้านบน';}};
